name: example-basic
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: /Cypress-Auto
          command: npx run cy:demo_skill